Daniel/test sets
TI-Tokyo/riak-java-client pull request #6
Opened 2022-11-29 05:26 UTC by daniel020403

## Description
Added tests for Sets and GSets.

2022-11-29 08:46 UTC, pjaclark requested changes
testGSet needs to try and remove an item and fail.

After checking it updated, do the same as testSet by removing user2, and having that fail as we'd expect.

2022-12-01 05:13 UTC, daniel020403 commented
> testGSet needs to try and remove an item and fail.
> 
> After checking it updated, do the same as testSet by removing user2, and having that fail as we'd expect.

Exception test for when removing an item from a GSet added.
@pjaclark , let me know if that works for you.

2022-12-09 12:49 UTC, pjaclark commented on src/test/java/com/basho/riak/client/api/commands/itest/ITestDatatype.java
> +            client.execute(updateRemove);
After this, there should be an Assert that always fails as it should never get to the assert line due to an exception being thrown.

2022-12-09 12:49 UTC, pjaclark commented on src/test/java/com/basho/riak/client/api/commands/itest/ITestDatatype.java
> +        } catch (Exception e) {
Change to IllegalArgumentException and let others through.

2022-12-19 04:26 UTC, pjaclark commented
LGTM

2022-12-19 04:26 UTC, pjaclark approved these changes

2022-12-19 13:29 UTC, Bob-The-Marauder approved these changes
Java is not my strong suit but everything looks ok to me as far as I can see.

2022-12-19 13:58 UTC, merged